#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import subprocess
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "docs" / "SESSION_CONTEXT.md"
AUTO_START = "<!-- AUTO_SNAPSHOT_START -->"
AUTO_END = "<!-- AUTO_SNAPSHOT_END -->"

PROCESS_PATTERNS = (
    "scripts/main.py",
    "workflow_runner.py",
    "paper_trade",
    "score_sold_unsold_visuals.py",
    "stage_balanced_full_scrape.py",
    "full_scrape_sold_history.py",
    "daily_eventual_sales.py",
)

RECENT_PATHS = (
    "experiments/old/deal_finder/data/live_runs",
    "experiments/old/deal_finder/data/offline_runs",
    "experiments/old/photo_arbitrage/data/features",
    "experiments/old/photo_arbitrage/data/reports",
    "experiments/old/photo_arbitrage/data/candidates",
)


def run_text(command: list[str], *, timeout: int = 20) -> str:
    try:
        result = subprocess.run(
            command,
            cwd=ROOT,
            check=False,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=timeout,
        )
    except Exception as exc:
        return f"<unavailable: {type(exc).__name__}: {exc}>"
    return result.stdout.strip()


def git_snapshot() -> tuple[str, str, str]:
    branch = run_text(["git", "branch", "--show-current"])
    head = run_text(["git", "rev-parse", "--short", "HEAD"])
    status = run_text(["git", "status", "--short"])
    return branch, head, status


def active_processes() -> list[str]:
    output = run_text(["ps", "-eo", "pid,etime,pcpu,pmem,args"], timeout=10)
    rows = []
    for line in output.splitlines():
        if any(pattern in line for pattern in PROCESS_PATTERNS) and "save_context_snapshot.py" not in line:
            rows.append(line.rstrip())
    return rows


def latest_files(relative_root: str, *, limit: int = 12) -> list[tuple[float, int, str]]:
    base = ROOT / relative_root
    if not base.exists():
        return []
    rows: list[tuple[float, int, str]] = []
    for dirpath, dirnames, filenames in os.walk(base):
        # Keep this snapshot cheap even when experiment folders are large.
        dirnames[:] = sorted(dirnames)[:80]
        for filename in filenames:
            path = Path(dirpath) / filename
            try:
                stat = path.stat()
            except OSError:
                continue
            rows.append((stat.st_mtime, stat.st_size, str(path.relative_to(ROOT))))
    rows.sort(reverse=True)
    return rows[:limit]


def format_status(status: str) -> str:
    if not status.strip():
        return "_clean_"
    lines = status.splitlines()
    if len(lines) > 80:
        lines = [*lines[:80], f"... truncated {len(lines) - 80} more lines"]
    return "```text\n" + "\n".join(lines) + "\n```"


def build_snapshot() -> str:
    now = datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")
    branch, head, status = git_snapshot()
    processes = active_processes()
    chunks = [
        AUTO_START,
        "",
        f"_Generated by `python3 scripts/save_context_snapshot.py` at `{now}`._",
        "",
        "## Auto Snapshot",
        "",
        f"- Git branch: `{branch or '<unknown>'}`",
        f"- Git HEAD: `{head or '<unknown>'}`",
        "",
        "### Git Status",
        "",
        format_status(status),
        "",
        "### Active Project Processes",
        "",
    ]
    if processes:
        chunks.append("```text")
        chunks.extend(processes)
        chunks.append("```")
    else:
        chunks.append("_No matching long-running project processes found._")
    chunks.extend(["", "### Recent Experiment Files", ""])
    for relative_root in RECENT_PATHS:
        chunks.append(f"#### `{relative_root}`")
        files = latest_files(relative_root)
        if not files:
            chunks.append("")
            chunks.append("_No files found._")
            chunks.append("")
            continue
        chunks.append("")
        for mtime, size, path in files:
            stamp = datetime.fromtimestamp(mtime).astimezone().isoformat(timespec="seconds")
            chunks.append(f"- `{stamp}` `{size}` bytes `{path}`")
        chunks.append("")
    chunks.extend(
        [
            "### Useful Resume Commands",
            "",
            "```bash",
            "python3 scripts/save_context_snapshot.py",
            "ps -ef | rg 'scripts/main.py|paper_trade|score_sold_unsold_visuals.py|stage_balanced_full_scrape.py'",
            "find experiments/current experiments/old -path '*/data/*' -type f -mmin -120 | sort",
            "```",
            "",
            AUTO_END,
            "",
        ]
    )
    return "\n".join(chunks)


def default_context() -> str:
    return f"""# Session Context

This file is the handoff note for long Codex conversations. Use it when a chat is getting too long or before starting a risky/large phase.

## How To Resume

In a new chat, start with:

```text
Read docs/SESSION_CONTEXT.md first, then continue from the current project state.
Do not delete existing data, do not edit private config files, and preserve running experiment outputs.
```

## Manual Context

Update this section manually when project goals, decisions, or unfinished tasks change.

### Current Goals

- Continue the Vinted deal-finder work using local historical data and public listing snapshots.
- Keep deal-finder experiment outputs under `experiments/old/deal_finder/data/`.
- Continue the photo-improvement track under `experiments/old/photo_arbitrage/data/`.
- Preserve production data and private configuration files.

### Active Work

- Normal scraping may be running through `scripts/main.py`.
- Full item/seller enrichment may be running through `scripts/stage_balanced_full_scrape.py`.
- Photo visual scoring may be running through `experiments/old/photo_arbitrage/score_sold_unsold_visuals.py`.

### Important Safety Rules

- Do not delete existing data.
- Do not edit `.env`, credentials, private config, or account settings.
- Do not make purchases, send messages, contact sellers, or perform account actions.
- Avoid overwriting production CSVs unless Ale explicitly approves it.
- Keep prompt wording focused on local data analysis, ranking, experiments, and public listing snapshots.

### Last Human Summary

- Add concise notes here before switching chats.
- Include what was running, what just changed, what failed, and the next recommended step.

{AUTO_START}

_Run `python3 scripts/save_context_snapshot.py` to refresh this section._

{AUTO_END}
"""


def update_context(path: Path) -> Path:
    snapshot = build_snapshot()
    if path.exists():
        text = path.read_text(encoding="utf-8")
    else:
        text = default_context()
    if AUTO_START in text and AUTO_END in text:
        before = text.split(AUTO_START, 1)[0]
        after = text.split(AUTO_END, 1)[1]
        updated = before.rstrip() + "\n\n" + snapshot.rstrip() + "\n" + after
    else:
        updated = text.rstrip() + "\n\n" + snapshot
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(updated, encoding="utf-8")
    tmp.replace(path)
    return path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Refresh docs/SESSION_CONTEXT.md with current local project state.")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="Markdown file to update.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    path = Path(args.output)
    if not path.is_absolute():
        path = ROOT / path
    updated = update_context(path)
    print(f"Updated {updated}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
